# Generated by Django 2.0 on 2018-10-26 04:40

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='to_member')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Chit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=30)),
                ('amount', models.PositiveIntegerField()),
                ('commission', models.PositiveIntegerField()),
                ('member_limit', models.PositiveSmallIntegerField()),
                ('date_to_allot', models.DateField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='member')),
                ('date_collected', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField()),
                ('chit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chitfund.Chit')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('phoneno', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chitfund.Contact'),
        ),
        migrations.AddField(
            model_name='chit',
            name='members',
            field=models.ManyToManyField(related_name='members', to='Chitfund.Contact'),
        ),
        migrations.AddField(
            model_name='chit',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='Chitfund.Contact'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='chit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chitfund.Chit'),
        ),
        migrations.AddField(
            model_name='allotment',
            name='to_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chitfund.Contact'),
        ),
    ]
