# Generated by Django 2.0 on 2018-10-26 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chitfund', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='chit',
        ),
        migrations.AddField(
            model_name='allotment',
            name='installment',
            field=models.PositiveIntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='allotment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Chitfund.Allotment'),
            preserve_default=False,
        ),
    ]
