# Generated by Django 2.0 on 2018-10-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chitfund', '0003_auto_20181026_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotment',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
