# Generated by Django 2.0 on 2018-10-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chitfund', '0004_allotment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
