# Generated by Django 2.0 on 2018-10-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chitfund', '0005_auto_20181027_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
